const express = require('express');
const router = express.Router();
const { sendMessage, getChatHistory, getChat, deleteChat, reviewResume, generateStudyPlan } = require('../controllers/chatController');
const { protect } = require('../middleware/authMiddleware');
router.post('/send', protect, sendMessage);
router.get('/history', protect, getChatHistory);
router.get('/:id', protect, getChat);
router.delete('/:id', protect, deleteChat);
router.post('/review-resume', protect, reviewResume);
router.post('/study-plan', protect, generateStudyPlan);
module.exports = router;
